version: '3.8'

services:
  lab-grpc-spring-boot-server:
    container_name: lab-grpc-spring-boot-server
    image: lab-grpc/spring-boot-server
    build:
      context: ./
      dockerfile: ./Dockerfile.server
    ports:
      - "9090:9090"
  lab-grpc-envoy:
    container_name: lab-grpc-envoy
    image: lab-grpc/envoy
    build:
      context: ./lab-grpc-envoy
    expose:
      - "8080"
    ports:
      - "8080:8080"
  lab-grpc-react-client:
    container_name: lab-grpc-react-client
    image: lab-grpc/react-client
    build:
      context: ./
      dockerfile: ./Dockerfile.client
    ports:
      - "3000:3000"
    depends_on:
      - lab-grpc-spring-boot-server
      - lab-grpc-envoy